"""Add escrow_address and allow_escrow_revert to jobs table

Revision ID: 2dc01b84276b
Revises: 
Create Date: 2025-11-09 07:04:14.408910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc01b84276b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('escrow_address', sa.String(length=42), nullable=True))
    op.add_column('jobs', sa.Column('allow_escrow_revert', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_jobs_escrow_address'), 'jobs', ['escrow_address'], unique=False)
    op.create_unique_constraint('unique_user_saved_job', 'saved_jobs', ['user_address', 'job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_saved_job', 'saved_jobs', type_='unique')
    op.drop_index(op.f('ix_jobs_escrow_address'), table_name='jobs')
    op.drop_column('jobs', 'allow_escrow_revert')
    op.drop_column('jobs', 'escrow_address')
    # ### end Alembic commands ###

